// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/vue/browsing-context-boundaries.vue
<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";

import {
  runBrowsingContextBoundaryCase,
  type BrowsingContextBoundaryResult,
} from "../shared/browsing-context-boundaries";
import { assertFixture, captureFrame, markReady } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const host = ref<HTMLElement>();
const result = ref<BrowsingContextBoundaryResult>();

onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  assertFixture(host.value, "Vue browsing-context host exists");
  result.value = await runBrowsingContextBoundaryCase(host.value, props.meta, props.spec, (name) =>
    captureFrame(props.meta, name),
  );
  await nextTick();
  markReady(props.meta, ["mounted", "vue-browsing-context-ready"]);
});
</script>

<template>
  <main
    id="smoke-root"
    data-framework="vue"
    :data-family="meta.family"
    :data-mode="result?.status ?? 'loading'"
  >
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <div ref="host" data-boundary-host></div>
      <dl v-if="result" data-boundary-facts>
        <div v-for="item in result.facts" :key="item.name" :data-fact="item.name">
          <dt>{{ item.name }}</dt>
          <dd>{{ item.value }}</dd>
        </div>
      </dl>
    </section>
  </main>
</template>

// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/angular/browsing-context-boundaries.ts
import { Component, signal, type Type } from "@angular/core";

import {
  runBrowsingContextBoundaryCase,
  type BrowsingContextBoundaryResult,
} from "../shared/browsing-context-boundaries";
import { assertFixture, captureFrame } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";
import { bootstrapAngular } from "./support";

interface BrowsingContextBoundaryComponent {
  result: ReturnType<typeof signal<BrowsingContextBoundaryResult | undefined>>;
  run(): Promise<void>;
}

function componentType(meta: SmokeMeta, spec: CaseSpec): Type<BrowsingContextBoundaryComponent> {
  class AngularBrowsingContextBoundaryComponent implements BrowsingContextBoundaryComponent {
    readonly meta = meta;
    readonly result = signal<BrowsingContextBoundaryResult | undefined>(undefined);

    async run(): Promise<void> {
      const host = document.querySelector("[data-boundary-host]");
      assertFixture(host instanceof HTMLElement, "Angular browsing-context host exists");
      this.result.set(
        await runBrowsingContextBoundaryCase(host, meta, spec, (name) =>
          captureFrame(meta, name),
        ),
      );
    }
  }

  Component({
    selector: "smoke-root",
    standalone: true,
    template: `
      <main
        id="smoke-root"
        data-framework="angular"
        [attr.data-family]="meta.family"
        [attr.data-mode]="result()?.status ?? 'loading'"
      >
        <h1>{{ meta.title }}</h1>
        <section data-case-body>
          <div data-boundary-host></div>
          @if (result(); as current) {
            <dl data-boundary-facts>
              @for (item of current.facts; track item.name) {
                <div [attr.data-fact]="item.name">
                  <dt>{{ item.name }}</dt>
                  <dd>{{ item.value }}</dd>
                </div>
              }
            </dl>
          }
        </section>
      </main>
    `,
  })(AngularBrowsingContextBoundaryComponent);
  return AngularBrowsingContextBoundaryComponent;
}

export async function mount(meta: SmokeMeta, spec: CaseSpec): Promise<void> {
  await bootstrapAngular(
    componentType(meta, spec),
    meta,
    "angular-browsing-context-ready",
    (instance) => instance.run(),
  );
}
