// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/vue/network-storage-boundaries.vue
<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";

import { assertFixture, captureFrame, markReady } from "../shared/harness";
import {
  runNetworkStorageBoundaryCase,
  type NetworkStorageBoundaryResult,
} from "../shared/network-storage-boundaries";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const host = ref<HTMLElement>();
const result = ref<NetworkStorageBoundaryResult>();

onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  assertFixture(host.value, "Vue network/storage host exists");
  result.value = await runNetworkStorageBoundaryCase(
    host.value,
    props.meta,
    props.spec,
    (name) => captureFrame(props.meta, name),
  );
  await nextTick();
  markReady(props.meta, ["mounted", "vue-network-storage-ready"]);
});
</script>

<template>
  <main
    id="smoke-root"
    data-framework="vue"
    :data-family="meta.family"
    :data-mode="result?.status ?? 'loading'"
  >
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <div ref="host" data-platform-host></div>
      <dl v-if="result" data-platform-facts>
        <div v-for="item in result.facts" :key="item.name" :data-fact="item.name">
          <dt>{{ item.name }}</dt>
          <dd>{{ item.value }}</dd>
        </div>
      </dl>
    </section>
  </main>
</template>

// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/angular/network-storage-boundaries.ts
import { Component, signal, type Type } from "@angular/core";

import { assertFixture, captureFrame } from "../shared/harness";
import {
  runNetworkStorageBoundaryCase,
  type NetworkStorageBoundaryResult,
} from "../shared/network-storage-boundaries";
import type { CaseSpec, SmokeMeta } from "../shared/types";
import { bootstrapAngular } from "./support";

interface NetworkStorageBoundaryComponent {
  result: ReturnType<typeof signal<NetworkStorageBoundaryResult | undefined>>;
  run(): Promise<void>;
}

function componentType(meta: SmokeMeta, spec: CaseSpec): Type<NetworkStorageBoundaryComponent> {
  class AngularNetworkStorageBoundaryComponent implements NetworkStorageBoundaryComponent {
    readonly meta = meta;
    readonly result = signal<NetworkStorageBoundaryResult | undefined>(undefined);

    async run(): Promise<void> {
      const host = document.querySelector("[data-platform-host]");
      assertFixture(host instanceof HTMLElement, "Angular network/storage host exists");
      this.result.set(
        await runNetworkStorageBoundaryCase(host, meta, spec, (name) =>
          captureFrame(meta, name),
        ),
      );
    }
  }

  Component({
    selector: "smoke-root",
    standalone: true,
    template: `
      <main
        id="smoke-root"
        data-framework="angular"
        [attr.data-family]="meta.family"
        [attr.data-mode]="result()?.status ?? 'loading'"
      >
        <h1>{{ meta.title }}</h1>
        <section data-case-body>
          <div data-platform-host></div>
          @if (result(); as current) {
            <dl data-platform-facts>
              @for (item of current.facts; track item.name) {
                <div [attr.data-fact]="item.name">
                  <dt>{{ item.name }}</dt>
                  <dd>{{ item.value }}</dd>
                </div>
              }
            </dl>
          }
        </section>
      </main>
    `,
  })(AngularNetworkStorageBoundaryComponent);
  return AngularNetworkStorageBoundaryComponent;
}

export async function mount(meta: SmokeMeta, spec: CaseSpec): Promise<void> {
  await bootstrapAngular(
    componentType(meta, spec),
    meta,
    "angular-network-storage-ready",
    (instance) => instance.run(),
  );
}
