// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/vue/state-and-batching.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from "vue";

import { money, stableItems } from "../shared/data";
import { captureFrame, markReady } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const count = ref(0);
const enabled = ref(false);
const reduced = ref(props.spec.seed);
const items = stableItems(props.spec.seed, Math.max(4, props.spec.size));
const total = computed(() => items.reduce((sum, item) => sum + item.amount, 0) + count.value);
const summaries = computed(() => [["count", String(count.value)], ["enabled", String(enabled.value)], ["reduced", String(reduced.value)], ["total", money(total.value)]]);
onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  count.value += 1;
  count.value += 2;
  count.value += props.spec.variant + 3;
  enabled.value = true;
  reduced.value += 5 + props.spec.variant;
  await nextTick();
  markReady(props.meta, ["mounted", "vue-batched-state-commit"]);
});
</script>

<template>
  <main id="smoke-root" data-framework="vue" :data-family="meta.family" :data-count="count">
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <output v-if="spec.variant === 0" aria-label="count">{{ count }}</output>
      <p v-else-if="spec.variant === 1" :data-batch-result="count">Three queued increments: {{ count }}</p>
      <p v-else-if="spec.variant === 2">Derived total <strong>{{ money(total) }}</strong></p>
      <div v-else-if="spec.variant === 3" role="switch" :aria-checked="enabled" :data-state="enabled ? 'on' : 'off'">Feature {{ enabled ? "enabled" : "disabled" }}</div>
      <p v-else-if="spec.variant === 4">Reducer value <b>{{ reduced }}</b></p>
      <dl v-else-if="spec.variant === 5"><dt>Gross</dt><dd>{{ money(total) }}</dd><dt>Net</dt><dd>{{ money(total - reduced) }}</dd></dl>
      <ol v-else-if="spec.variant === 6"><li v-for="[name, value] in summaries" :key="name" :data-key="name">{{ name }}: {{ value }}</li></ol>
      <section v-else-if="spec.variant === 7"><h2>Computed summary</h2><p v-for="item in items.slice(0, 8)" :key="item.id">{{ item.title }}: {{ money(item.amount + count) }}</p></section>
      <div v-else-if="spec.variant === 8" :data-machine-state="enabled ? 'settled' : 'booting'"><h2>{{ enabled ? "Settled" : "Booting" }}</h2><p>Transition #{{ reduced }}</p></div>
      <div v-else class="metrics"><article v-for="index in 16" :key="index"><h2>Metric {{ index }}</h2><strong>{{ total + (index - 1) * reduced }}</strong><small>{{ enabled ? "live" : "idle" }}</small></article></div>
    </section>
  </main>
</template>

// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/react/state-and-batching.tsx
import { useEffect, useMemo, useReducer, useState } from "react";

import { money, stableItems } from "../shared/data";
import { markReady } from "../shared/harness";
import { mountReact, type ReactCaseProps, useFrameUpdate } from "./support";

function reducer(value: number, action: { amount: number }) {
  return value + action.amount;
}

function StateCase({ meta, spec }: ReactCaseProps) {
  const [count, setCount] = useState(0);
  const [enabled, setEnabled] = useState(false);
  const [reduced, dispatch] = useReducer(reducer, spec.seed);
  const items = useMemo(() => stableItems(spec.seed, Math.max(4, spec.size)), [spec.seed, spec.size]);
  const total = useMemo(() => items.reduce((sum, item) => sum + item.amount, 0) + count, [count, items]);
  useFrameUpdate(meta, () => {
    setCount((value) => value + 1);
    setCount((value) => value + 2);
    setCount((value) => value + spec.variant + 3);
    setEnabled(true);
    dispatch({ amount: 5 });
    dispatch({ amount: spec.variant });
  }, [spec.variant]);
  useEffect(() => {
    if (enabled && count > 0) markReady(meta, ["mounted", "react-batched-state-commit"]);
  }, [count, enabled, meta]);

  const summaries = [
    ["count", String(count)],
    ["enabled", String(enabled)],
    ["reduced", String(reduced)],
    ["total", money(total)],
  ];
  let body;
  if (spec.variant === 0) body = <output aria-label="count">{count}</output>;
  else if (spec.variant === 1) body = <p data-batch-result={count}>Three queued increments: {count}</p>;
  else if (spec.variant === 2) body = <p>Derived total <strong>{money(total)}</strong></p>;
  else if (spec.variant === 3) body = <div role="switch" aria-checked={enabled} data-state={enabled ? "on" : "off"}>Feature {enabled ? "enabled" : "disabled"}</div>;
  else if (spec.variant === 4) body = <p>Reducer value <b>{reduced}</b></p>;
  else if (spec.variant === 5) body = <dl><dt>Gross</dt><dd>{money(total)}</dd><dt>Net</dt><dd>{money(total - reduced)}</dd></dl>;
  else if (spec.variant === 6) body = <ol>{summaries.map(([name, value]) => <li key={name} data-key={name}>{name}: {value}</li>)}</ol>;
  else if (spec.variant === 7) body = <section><h2>Memo summary</h2>{items.slice(0, 8).map((item) => <p key={item.id}>{item.title}: {money(item.amount + count)}</p>)}</section>;
  else if (spec.variant === 8) body = <div data-machine-state={enabled ? "settled" : "booting"}><h2>{enabled ? "Settled" : "Booting"}</h2><p>Transition #{reduced}</p></div>;
  else body = <div className="metrics">{Array.from({ length: 16 }, (_, index) => <article key={index}><h2>Metric {index + 1}</h2><strong>{total + index * reduced}</strong><small>{enabled ? "live" : "idle"}</small></article>)}</div>;
  return <main id="smoke-root" data-framework="react" data-family={meta.family} data-count={count}><h1>{meta.title}</h1><section data-case-body>{body}</section></main>;
}

export function mount(meta: ReactCaseProps["meta"], spec: ReactCaseProps["spec"]): void {
  mountReact(StateCase, meta, spec);
}
