// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/angular/collections.ts
import { Component, signal, type Type } from "@angular/core";

import { money, stableItems, type StableItem } from "../shared/data";
import type { CaseSpec, SmokeMeta } from "../shared/types";
import { bootstrapAngular } from "./support";

interface CollectionsComponent {
  items: ReturnType<typeof signal<StableItem[]>>;
  source: StableItem[];
}

function componentType(meta: SmokeMeta, spec: CaseSpec): Type<CollectionsComponent> {
  class AngularCollectionsComponent implements CollectionsComponent {
    readonly meta = meta;
    readonly spec = spec;
    readonly source = stableItems(spec.seed, spec.variant === 9 ? 48 : Math.max(5, spec.size));
    readonly items = signal([...this.source]);
    readonly statuses = ["new", "active", "paused", "done"] as const;
    readonly String = String;
    readonly money = money;
    byStatus(status: string) { return this.items().filter((item) => item.status === status); }
  }
  Component({
    selector: "smoke-root",
    standalone: true,
    template: `
      <main id="smoke-root" data-framework="angular" [attr.data-family]="meta.family">
        <h1>{{ meta.title }}</h1><section data-case-body>
          @if (spec.variant <= 3) {
            <ul [attr.data-count]="items().length">@for (item of items(); track item.id) { <li [attr.data-id]="item.id" [attr.data-status]="item.status"><strong>{{ item.title }}</strong><span>{{ item.owner }}</span></li> }</ul>
          } @else if (spec.variant === 4) {
            @for (status of statuses; track status) { <section><h2>{{ status }}</h2><ul>@for (item of byStatus(status); track item.id) { <li><strong>{{ item.title }}</strong><span>{{ item.owner }}</span></li> }</ul></section> }
          } @else if (spec.variant === 5) {
            <ul>@for (item of items().slice(0, 6); track item.id; let index = $index) { <li><span>{{ item.title }}</span>@if (index < 3) { <ul><li>{{ item.owner }}</li><li>{{ item.tags.join(" / ") }}</li></ul> }</li> }</ul>
          } @else if (spec.variant === 6 || spec.variant === 9) {
            <table><thead><tr><th>Item</th><th>Owner</th><th>Status</th><th>Amount</th></tr></thead><tbody>@for (item of items(); track item.id) { <tr><th scope="row">{{ item.title }}</th><td>{{ item.owner }}</td><td>{{ item.status }}</td><td>{{ money(item.amount) }}</td></tr> }</tbody></table>
          } @else if (spec.variant === 7) {
            <div role="list" class="card-grid">@for (item of items(); track item.id) { <article role="listitem"><h2>{{ item.title }}</h2><p>{{ item.owner }}</p><div>@for (tag of item.tags; track tag) { <span>{{ tag }}</span> }</div></article> }</div>
          } @else {
            <ol class="activity-feed">@for (item of items(); track item.id; let index = $index) { <li><time [attr.datetime]="'2026-07-' + String(index + 1).padStart(2, '0')">Day {{ index + 1 }}</time><p><b>{{ item.owner }}</b> moved {{ item.title }} to {{ item.status }}</p></li> }</ol>
          }
        </section>
      </main>
    `,
  })(AngularCollectionsComponent);
  return AngularCollectionsComponent;
}

export async function mount(meta: SmokeMeta, spec: CaseSpec): Promise<void> {
  await bootstrapAngular(componentType(meta, spec), meta, "angular-keyed-collection-update", (instance) => {
    if (spec.variant === 1) instance.items.set([...instance.source].reverse());
    else if (spec.variant === 2) instance.items.set([{ ...instance.source[0], id: `prepended-${spec.seed}`, title: "Prepended checkpoint" }, ...instance.source]);
    else if (spec.variant === 3) instance.items.set(instance.source.filter((_, index) => index % 2 === 0));
    else instance.items.set(instance.source.map((item, index) => index === 1 ? { ...item, status: "done" } : item));
  });
}

// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/vue/collections.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from "vue";

import { money, stableItems } from "../shared/data";
import { captureFrame, markReady } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const source = stableItems(props.spec.seed, props.spec.variant === 9 ? 48 : Math.max(5, props.spec.size));
const items = ref([...source]);
const statuses = ["new", "active", "paused", "done"];
const groups = computed(() => statuses.map((status) => ({ status, items: items.value.filter((item) => item.status === status) })));
onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  if (props.spec.variant === 1) items.value = [...source].reverse();
  else if (props.spec.variant === 2) items.value = [{ ...source[0], id: `prepended-${props.spec.seed}`, title: "Prepended checkpoint" }, ...source];
  else if (props.spec.variant === 3) items.value = source.filter((_, index) => index % 2 === 0);
  else items.value = source.map((item, index) => index === 1 ? { ...item, status: "done" } : item);
  await nextTick();
  markReady(props.meta, ["mounted", "vue-keyed-collection-update"]);
});
</script>

<template>
  <main id="smoke-root" data-framework="vue" :data-family="meta.family">
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <ul v-if="spec.variant <= 3" :data-count="items.length"><li v-for="item in items" :key="item.id" :data-id="item.id" :data-status="item.status"><strong>{{ item.title }}</strong><span>{{ item.owner }}</span></li></ul>
      <template v-else-if="spec.variant === 4"><section v-for="group in groups" :key="group.status"><h2>{{ group.status }}</h2><ul><li v-for="item in group.items" :key="item.id"><strong>{{ item.title }}</strong><span>{{ item.owner }}</span></li></ul></section></template>
      <ul v-else-if="spec.variant === 5"><li v-for="(item, index) in items.slice(0, 6)" :key="item.id"><span>{{ item.title }}</span><ul v-if="index < 3"><li>{{ item.owner }}</li><li>{{ item.tags.join(" / ") }}</li></ul></li></ul>
      <table v-else-if="spec.variant === 6 || spec.variant === 9"><thead><tr><th>Item</th><th>Owner</th><th>Status</th><th>Amount</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><th scope="row">{{ item.title }}</th><td>{{ item.owner }}</td><td>{{ item.status }}</td><td>{{ money(item.amount) }}</td></tr></tbody></table>
      <div v-else-if="spec.variant === 7" role="list" class="card-grid"><article v-for="item in items" :key="item.id" role="listitem"><h2>{{ item.title }}</h2><p>{{ item.owner }}</p><div><span v-for="tag in item.tags" :key="tag">{{ tag }}</span></div></article></div>
      <ol v-else class="activity-feed"><li v-for="(item, index) in items" :key="item.id"><time :datetime="`2026-07-${String(index + 1).padStart(2, '0')}`">Day {{ index + 1 }}</time><p><b>{{ item.owner }}</b> moved {{ item.title }} to {{ item.status }}</p></li></ol>
    </section>
  </main>
</template>
