// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/angular/components.ts
import { Component, InjectionToken, inject, signal, type Type } from "@angular/core";

import { stableItems } from "../shared/data";
import type { CaseSpec, SmokeMeta } from "../shared/types";
import { bootstrapAngular } from "./support";

const THEME = new InjectionToken<string>("smoke-theme");

class BadgeComponent {
  label = "";
}
Component({
  selector: "smoke-badge",
  standalone: true,
  inputs: ["label"],
  template: `<span class="badge">{{ label }}</span>`,
})(BadgeComponent);

interface ComponentsComponent {
  active: ReturnType<typeof signal<number>>;
}

function componentType(meta: SmokeMeta, spec: CaseSpec): Type<ComponentsComponent> {
  class AngularComponentsComponent implements ComponentsComponent {
    readonly meta = meta;
    readonly spec = spec;
    readonly active = signal(0);
    readonly items = stableItems(spec.seed, Math.max(5, spec.size));
    readonly theme = inject(THEME);
    activeLabel() { return ["Overview", "Network", "Runtime"][this.active()]; }
  }
  Component({
    selector: "smoke-root",
    standalone: true,
    imports: [BadgeComponent],
    providers: [{ provide: THEME, useValue: "ocean" }],
    template: `
      <main id="smoke-root" data-framework="angular" [attr.data-family]="meta.family">
        <h1>{{ meta.title }}</h1><section data-case-body>
          @switch (spec.variant) {
            @case (0) { <smoke-badge [label]="'Input value ' + spec.seed" /> }
            @case (1) { <article><h2>Parent</h2><section><h3>Child</h3><smoke-badge label="Grandchild" /></section></article> }
            @case (2) { <article [attr.data-theme]="theme"><h2>Injection consumer</h2></article> }
            @case (3) { <section><header><smoke-badge label="Header projection" /></header><main>@for (item of items.slice(0, 3); track item.id) { <p>{{ item.title }}</p> }</main><footer>Footer projection</footer></section> }
            @case (4) { @if (active() === 1) { <article data-component="alpha">Alpha component</article> } @else { <aside data-component="beta">Beta component</aside> } }
            @case (5) { <ul><li data-depth="0">{{ items[0].title }}<ul><li data-depth="1">{{ items[1].title }}<ul><li data-depth="2">{{ items[2].title }}<ul><li data-depth="3">{{ items[3].title }}</li></ul></li></ul></li></ul></li></ul> }
            @case (6) { <section><p>Local content</p><aside id="portal-content">Dynamic host {{ spec.seed }}</aside></section> }
            @case (7) { <div role="group"><smoke-badge label="Prefix" /><button>Action</button><smoke-badge label="Suffix" /></div> }
            @case (8) { <section><div role="tablist">@for (label of ["Overview", "Network", "Runtime"]; track label; let index = $index) { <button role="tab" [attr.aria-selected]="active() === index">{{ label }}</button> }</div><article role="tabpanel"><h2>{{ activeLabel() }}</h2><p>Selected panel {{ active() }}</p></article></section> }
            @default { <div class="app-shell"><header><h2>Moli Console</h2><smoke-badge label="online" /></header><nav>@for (item of items.slice(0, 5); track item.id) { <a [href]="'#' + item.id">{{ item.title }}</a> }</nav><section>@for (item of items.slice(5); track item.id) { <article><h3>{{ item.title }}</h3><p>{{ item.owner }}</p></article> }</section><footer>Build {{ spec.seed }}</footer></div> }
          }
        </section>
      </main>
    `,
  })(AngularComponentsComponent);
  return AngularComponentsComponent;
}

export async function mount(meta: SmokeMeta, spec: CaseSpec): Promise<void> {
  await bootstrapAngular(componentType(meta, spec), meta, "angular-component-composition", (instance) => {
    instance.active.set((spec.variant + 1) % 3);
  });
}

// core-deps/dataworm/integrations/moli/moli-frontend-smoke/src/vue/components.vue
<script setup lang="ts">
import { computed, defineComponent, h, inject, nextTick, onMounted, provide, ref } from "vue";

import { stableItems, type StableItem } from "../shared/data";
import { captureFrame, markReady } from "../shared/harness";
import type { CaseSpec, SmokeMeta } from "../shared/types";

const props = defineProps<{ meta: SmokeMeta; spec: CaseSpec }>();
const active = ref(0);
const items = stableItems(props.spec.seed, Math.max(5, props.spec.size));
provide("theme", "ocean");
const contextTheme = inject("theme", "unset");
const activeLabel = computed(() => ["Overview", "Network", "Runtime"][active.value]);
const Badge = defineComponent({ props: { label: { type: String, required: true } }, setup(componentProps) { return () => h("span", { class: "badge" }, componentProps.label); } });
const TreeNode = defineComponent({
  name: "TreeNode",
  props: { item: { type: Object as () => StableItem, required: true }, depth: { type: Number, required: true } },
  setup(componentProps) {
    return () => h("li", { "data-depth": componentProps.depth }, [
      h("span", componentProps.item.title),
      componentProps.depth < 3 ? h("ul", [h(TreeNode, { item: { ...componentProps.item, id: `${componentProps.item.id}-${componentProps.depth}` }, depth: componentProps.depth + 1 })]) : null,
    ]);
  },
});
onMounted(async () => {
  await captureFrame(props.meta, "mounted");
  active.value = (props.spec.variant + 1) % 3;
  await nextTick();
  markReady(props.meta, ["mounted", "vue-component-composition"]);
});
</script>

<template>
  <main id="smoke-root" data-framework="vue" :data-family="meta.family">
    <h1>{{ meta.title }}</h1>
    <section data-case-body>
      <Badge v-if="spec.variant === 0" :label="`Input value ${spec.seed}`" />
      <article v-else-if="spec.variant === 1"><h2>Parent</h2><section><h3>Child</h3><Badge label="Grandchild" /></section></article>
      <article v-else-if="spec.variant === 2" :data-theme="contextTheme"><h2>Provide consumer</h2></article>
      <section v-else-if="spec.variant === 3"><header><Badge label="Header slot" /></header><div><p v-for="item in items.slice(0, 3)" :key="item.id">{{ item.title }}</p></div><footer>Footer slot</footer></section>
      <component :is="active === 1 ? 'article' : 'aside'" v-else-if="spec.variant === 4" :data-component="active === 1 ? 'alpha' : 'beta'">{{ active === 1 ? "Alpha component" : "Beta component" }}</component>
      <ul v-else-if="spec.variant === 5"><TreeNode :item="items[0]" :depth="0" /></ul>
      <section v-else-if="spec.variant === 6"><p>Local content</p><Teleport to="#portal-host"><aside id="portal-content">Portal {{ spec.seed }}</aside></Teleport></section>
      <div v-else-if="spec.variant === 7" role="group"><Badge label="Prefix" /><button>Action</button><Badge label="Suffix" /></div>
      <section v-else-if="spec.variant === 8"><div role="tablist"><button v-for="(label, index) in ['Overview', 'Network', 'Runtime']" :key="label" role="tab" :aria-selected="active === index">{{ label }}</button></div><article role="tabpanel"><h2>{{ activeLabel }}</h2><p>Selected panel {{ active }}</p></article></section>
      <div v-else class="app-shell"><header><h2>Moli Console</h2><Badge label="online" /></header><nav><a v-for="item in items.slice(0, 5)" :key="item.id" :href="`#${item.id}`">{{ item.title }}</a></nav><section><article v-for="item in items.slice(5)" :key="item.id"><h3>{{ item.title }}</h3><p>{{ item.owner }}</p></article></section><footer>Build {{ spec.seed }}</footer></div>
    </section>
  </main>
  <div id="portal-host"></div>
</template>
